[project]
name = "grab_tools_stats"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
	"aiohttp",
	"requests",
	"discord.py",
]

[project.optional-dependencies]
dev = [
	"black",        # formatter
	"basedpyright", # lsp
	"ruff",         # linter
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# black formatter
[tool.black]
line-length = 88
target-version = ['py313']

# ruff linter
[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = [
	"E",   # pycodestyle errors
	"F",   # pyflakes
	"I",   # import sorting
	"UP",  # pyupgrade
	"B",   # bugbear
	"SIM", # simplify
	"W",   # pycodestyle warnings
]

# basedpyright lsp
[tool.pyright]
typeCheckingMode = "all"

reportMissingImports = true
reportUnusedVariable = true
reportUnusedImport = true

reportAny = false
reportUnannotatedClassAttribute = false
