name: Update statistics

on:
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/run-python.yml
    with:
      script: scripts/statistics.py
      args: "${{ secrets.SERVER_TOKEN_HEADERS }}"
