name: Main update

on:
  workflow_dispatch:
  schedule:
    # every day at 5
    - cron: "0 5 * * *"

jobs:
  run:
    uses: ./.github/workflows/run-python.yml
    with:
      script: scripts/update.py
      args: ${{ secrets.SERVER_TOKEN_HEADERS }} #${{ secrets.BOT_TOKEN }}
