name: Main update

on:
  workflow_dispatch:
  # schedule:
  #   # every day at 5
  #   - cron: "0 5 * * *"

jobs:
  run:
    uses: ./.github/workflows/run-python.yml
    with:
      script: scripts/update.py
      args: ${{ secrets.BOT_TOKEN }} ${{ secrets.CF_ACCOUNT_ID }} ${{ secrets.CF_TOKEN }} ${{ secrets.NAMESPACE }}
